services:
  abnomalydetector:
    image: abnomalydetector:dev
    build:
      args:
        LAUNCHING_FROM_VS: true
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AbnomalyDetector"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/.nuget/fallbackpackages;/.nuget/fallbackpackages2
    volumes:
      - D:\Projects\API.Gateway\AbnomalyDetector:/app:rw
      - D:\Projects\API.Gateway:/src:rw
      - C:\Users\Behtash\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\Behtash\.nuget\packages:/.nuget/packages:ro
      - C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages:/.nuget/fallbackpackages:ro
      - D:\DevExpress\Components\Offline Packages:/.nuget/fallbackpackages2:ro
      - C:\Users\Behtash\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\Behtash\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\Behtash\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\Behtash\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages --additionalProbingPath /.nuget/fallbackpackages --additionalProbingPath /.nuget/fallbackpackages2  \"/app/bin/Debug/net8.0/AbnomalyDetector.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true
  apigateway:
    image: apigateway:dev
    build:
      args:
        LAUNCHING_FROM_VS: true
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "API.Gateway"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/.nuget/fallbackpackages;/.nuget/fallbackpackages2
    volumes:
      - D:\Projects\API.Gateway\API.Gateway:/app:rw
      - D:\Projects\API.Gateway:/src:rw
      - C:\Users\Behtash\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\Behtash\.nuget\packages:/.nuget/packages:ro
      - C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages:/.nuget/fallbackpackages:ro
      - D:\DevExpress\Components\Offline Packages:/.nuget/fallbackpackages2:ro
      - C:\Users\Behtash\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\Behtash\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\Behtash\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\Behtash\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages --additionalProbingPath /.nuget/fallbackpackages --additionalProbingPath /.nuget/fallbackpackages2  \"/app/bin/Debug/net8.0/API.Gateway.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true
